version: 2.1

orbs:
    codecov: codecov/codecov@1.0.2

jobs:
    build:
        docker:
            - image: circleci/golang:1.12
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - go-mod-v4-{{ checksum "go.sum" }}
            - run:
                  name: Install deps
                  command: |
                        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.3
            - run:
                  name: Run lints
                  command: make lint
            - run:
                  name: Run unit tests
                  command: make test
            - codecov/upload:
                file: coverage.out
            - save_cache:
                  key: go-mod-v4-{{ checksum "go.sum" }}
                  paths:
                      - "/go/pkg/mod"

workflows:
    version: 2.1
    build:
        jobs:
            - build